using System;
using System.Linq;
using System.Threading.Tasks;
using DataLinq.Attributes;
using DataLinq.Core.Factories;
using DataLinq.Metadata;
using ThrowAway.Extensions;

namespace DataLinq.Tests.Unit.Core;

public class GeneratorFileFactoryTests
{
    [Test]
    public async Task CreateModelFiles_DatabaseModel_EmitsOnlyGeneratedDatabaseMetadataBootstrapHook()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorDb.DataLinqMetadata.cs");

        await Assert.That(generatedFile.contents.Contains(
            "public partial class GeneratorDb : global::DataLinq.Interfaces.IDataLinqGeneratedDatabaseModel<GeneratorDb>"))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "public static global::DataLinq.Metadata.GeneratedDatabaseModelDeclaration GetDataLinqGeneratedModel() =>"))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "public static global::DataLinq.Core.Factories.MetadataDatabaseDraft GetDataLinqGeneratedMetadata() =>"))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "public static void SetDataLinqGeneratedMetadata(global::DataLinq.Metadata.DatabaseDefinition metadata)"))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "new(\"GeneratorModels\", typeof(global::TestNamespace.GeneratorModel), typeof(global::TestNamespace.ImmutableGeneratorModel), typeof(global::TestNamespace.MutableGeneratorModel), new global::System.Func<global::DataLinq.Instances.IRowData, global::DataLinq.Interfaces.IDataSourceAccess, global::DataLinq.Instances.IImmutableInstance>(global::TestNamespace.ImmutableGeneratorModel.NewDataLinqImmutableInstance), global::DataLinq.Metadata.TableType.Table),"))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "new global::DataLinq.Core.Factories.MetadataValuePropertyDraft("))
            .IsTrue();
        await Assert.That(generatedFile.contents.Contains(
            "public static global::DataLinq.Metadata.GeneratedTableModelDeclaration[] GetDataLinqGeneratedTableModels() =>"))
            .IsFalse();
    }

    [Test]
    public async Task CreateModelFiles_EmitsGeneratedPreambleWithoutCliStamp()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions
        {
            UseNullableReferenceTypes = true
        })
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents).StartsWith(
            """
            // <auto-generated />
            // This file was generated by DataLinq. Do not edit this file directly.
            #nullable enable

            using System;
            """);
        await Assert.That(generatedFile.contents).DoesNotContain("DataLinq CLI version:");
        await Assert.That(generatedFile.contents).DoesNotContain("Generated at (UTC):");
    }

    [Test]
    public async Task CreateModelFiles_DefaultOptions_EnableNullableReferenceTypes()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents).StartsWith(
            """
            // <auto-generated />
            // This file was generated by DataLinq. Do not edit this file directly.
            #nullable enable

            using System;
            """);
    }

    [Test]
    public async Task CreateModelFiles_ExplicitNullableOptOut_EmitsNullableDisable()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions
        {
            UseNullableReferenceTypes = false
        })
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents).StartsWith(
            """
            // <auto-generated />
            // This file was generated by DataLinq. Do not edit this file directly.
            #nullable disable

            using System;
            """);
    }

    [Test]
    public async Task CreateModelFiles_Model_EmitsIndexedGeneratedAccess()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents).Contains("protected const int DataLinqColumnIndex_Name = 0;");
        await Assert.That(generatedFile.contents).Contains("internal static global::DataLinq.Metadata.ColumnDefinition DataLinqColumn_Name { get; private set; } = null!;");
        await Assert.That(generatedFile.contents).Contains("internal static void SetDataLinqGeneratedModel(global::DataLinq.Metadata.ModelDefinition model)");
        await Assert.That(generatedFile.contents).Contains("GetValue(DataLinqColumnIndex_Name)");
        await Assert.That(generatedFile.contents).Contains("public MutableGeneratorModel() : base(GeneratorModel.DataLinqModel)");
        await Assert.That(generatedFile.contents).Contains("get => (string)GetValue(GeneratorModel.DataLinqColumn_Name)!");
        await Assert.That(generatedFile.contents).Contains("set => SetValue(GeneratorModel.DataLinqColumn_Name, value);");
        await Assert.That(generatedFile.contents).DoesNotContain("GetValue(nameof(");
        await Assert.That(generatedFile.contents).DoesNotContain("SetValue(nameof(");
    }

    [Test]
    public async Task CreateModelFiles_ImmutableModel_EmitsGeneratedFactoryHook()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated");

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents.Contains(
            "public static IImmutableInstance NewDataLinqImmutableInstance(IRowData rowData, IDataSourceAccess dataSource) => new ImmutableGeneratorModel(rowData, dataSource);"))
            .IsTrue();
    }

    [Test]
    public async Task CreateModelFiles_DefaultEnumValue_UsesEnumMember()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Status",
            propertyType: new CsTypeDeclaration("MyStatusEnum", "TestNamespace", ModelCsType.Enum),
            defaultValue: 2,
            enumProperty: new EnumProperty(
                enumValues: [("Active", 1), ("Inactive", 2)],
                csEnumValues: [("Active", 1), ("Inactive", 2)],
                declaredInClass: false));

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents.Contains("this.Status = MyStatusEnum.Inactive;")).IsTrue();
        await Assert.That(generatedFile.contents.Contains("this.Status = 2;")).IsFalse();
    }

    [Test]
    public async Task CreateModelFiles_DefaultLongValue_UsesLongLiteral()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Count",
            propertyType: new CsTypeDeclaration(typeof(long)),
            defaultValue: 1);

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents.Contains("this.Count = 1L;")).IsTrue();
        await Assert.That(generatedFile.contents.Contains("this.Count = 1;")).IsFalse();
    }

    [Test]
    public async Task CreateModelFiles_Comments_EmitXmlDocsInGeneratedTypes()
    {
        var database = CreateDatabaseWithDefaultValue(
            propertyName: "Name",
            propertyType: new CsTypeDeclaration(typeof(string)),
            defaultValue: "generated",
            includeComments: true);

        var generatedFile = new GeneratorFileFactory(new GeneratorFileFactoryOptions())
            .CreateModelFiles(database)
            .Single(file => file.path == "GeneratorModel.cs");

        await Assert.That(generatedFile.contents).Contains("/// Generated model &amp; docs");
        await Assert.That(generatedFile.contents).Contains("/// Generated property &lt;name&gt;");
    }

    private static DatabaseDefinition CreateDatabaseWithDefaultValue(
        string propertyName,
        CsTypeDeclaration propertyType,
        object defaultValue,
        EnumProperty? enumProperty = null,
        bool includeComments = false)
    {
        var propertyAttributes = new Attribute[] { new ColumnAttribute(propertyName.ToLowerInvariant()), new DefaultAttribute(defaultValue) };
        if (includeComments)
            propertyAttributes = [.. propertyAttributes, new CommentAttribute("Generated property <name>")];

        var modelAttributes = includeComments
            ? new Attribute[] { new CommentAttribute("Generated model & docs") }
            : [];

        var draft = new MetadataDatabaseDraft(
            "GeneratorDb",
            new CsTypeDeclaration("GeneratorDb", "TestNamespace", ModelCsType.Class))
        {
            TableModels =
            [
                new MetadataTableModelDraft(
                    "GeneratorModels",
                    new MetadataModelDraft(new CsTypeDeclaration("GeneratorModel", "TestNamespace", ModelCsType.Class))
                    {
                        Attributes = modelAttributes,
                        ValueProperties =
                        [
                            new MetadataValuePropertyDraft(
                                propertyName,
                                propertyType,
                                new MetadataColumnDraft(propertyName.ToLowerInvariant())
                                {
                                    PrimaryKey = true,
                                    DbTypes = [new DatabaseColumnType(DatabaseType.MySQL, "int")]
                                })
                            {
                                Attributes = propertyAttributes,
                                EnumProperty = enumProperty
                            }
                        ]
                    },
                    new MetadataTableDraft("generator_table"))
            ]
        };

        return new MetadataDefinitionFactory().Build(draft).ValueOrException();
    }
}
