using System;
using System.Collections.Generic;
using System.Globalization;

namespace DataLinq.Core.Factories;

public readonly struct GeneratedFileStamp
{
    public GeneratedFileStamp(string cliVersion, DateTimeOffset generatedAtUtc)
    {
        CliVersion = string.IsNullOrWhiteSpace(cliVersion) ? "unknown" : cliVersion;
        GeneratedAtUtc = generatedAtUtc.ToUniversalTime();
    }

    public string CliVersion { get; }
    public DateTimeOffset GeneratedAtUtc { get; }
}

public sealed class GeneratedFilePreambleOptions
{
    public bool UseNullableReferenceTypes { get; set; } = true;
    public GeneratedFileStamp? Stamp { get; set; }
}

public static class GeneratedFilePreamble
{
    public const string AutoGeneratedLine = "// <auto-generated />";
    public const string NoticeLine = "// This file was generated by DataLinq. Do not edit this file directly.";

    public static IEnumerable<string> Create(GeneratedFilePreambleOptions options)
    {
        if (options == null)
            throw new ArgumentNullException(nameof(options));

        yield return AutoGeneratedLine;
        yield return NoticeLine;

        if (options.Stamp.HasValue)
        {
            var stamp = options.Stamp.Value;
            yield return $"// DataLinq CLI version: {stamp.CliVersion}";
            yield return $"// Generated at (UTC): {stamp.GeneratedAtUtc.ToString("O", CultureInfo.InvariantCulture)}";
        }

        yield return options.UseNullableReferenceTypes ? "#nullable enable" : "#nullable disable";
        yield return "";
    }
}
