using System;
using System.Collections.Generic;
using System.Globalization;

namespace DataLinq.Core.Factories;

public readonly struct GeneratedFileStamp
{
    public GeneratedFileStamp(string cliVersion, DateTimeOffset generatedAtUtc)
    {
        CliVersion = string.IsNullOrWhiteSpace(cliVersion) ? "unknown" : cliVersion;
        GeneratedAtUtc = generatedAtUtc.ToUniversalTime();
    }

    public string CliVersion { get; }
    public DateTimeOffset GeneratedAtUtc { get; }
}

public sealed class GeneratedFilePreambleOptions
{
    public bool UseNullableReferenceTypes { get; set; } = true;
    public GeneratedFileStamp? Stamp { get; set; }
    public GeneratedFilePreambleKind Kind { get; set; } = GeneratedFilePreambleKind.CompilerGeneratedImplementation;
}

public enum GeneratedFilePreambleKind
{
    ModelDeclaration,
    CompilerGeneratedImplementation
}

public static class GeneratedFilePreamble
{
    public const string AutoGeneratedLine = "// <auto-generated />";
    public const string ModelDeclarationNoticeLine = "// Generated by DataLinq. Supported model class names, property names, relation names, and C# property types may be edited.";
    public const string ModelDeclarationDocumentationLine = "// See https://datalinq.org/docs/model-generation.html#editing-generated-models before changing mapping attributes or using --fresh.";
    public const string CompilerGeneratedImplementationNoticeLine = "// Generated by DataLinq. Do not edit this compiler-generated implementation file.";

    public static IEnumerable<string> Create(GeneratedFilePreambleOptions options)
    {
        if (options == null)
            throw new ArgumentNullException(nameof(options));

        yield return AutoGeneratedLine;

        if (options.Kind == GeneratedFilePreambleKind.ModelDeclaration)
        {
            yield return ModelDeclarationNoticeLine;
            yield return ModelDeclarationDocumentationLine;
        }
        else
        {
            yield return CompilerGeneratedImplementationNoticeLine;
        }

        if (options.Stamp.HasValue)
        {
            var stamp = options.Stamp.Value;
            yield return $"// DataLinq CLI version: {stamp.CliVersion}";
            yield return $"// Generated at (UTC): {stamp.GeneratedAtUtc.ToString("O", CultureInfo.InvariantCulture)}";
        }

        yield return options.UseNullableReferenceTypes ? "#nullable enable" : "#nullable disable";
        yield return "";
    }
}
