using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using DataLinq.Attributes;
using DataLinq.MariaDB;
using DataLinq.Metadata;
using DataLinq.MySql;
using DataLinq.SQLite;
using DataLinq.Validation;

namespace DataLinq.Tools;

public sealed class SchemaDiffScriptGenerator
{
    private static readonly string[] MySqlNoLengthTypes =
    [
        "text",
        "tinytext",
        "mediumtext",
        "longtext",
        "enum",
        "float",
        "double",
        "blob",
        "tinyblob",
        "mediumblob",
        "longblob"
    ];

    public string Generate(DatabaseType databaseType, IReadOnlyList<SchemaDifference> differences)
    {
        var builder = new StringBuilder();
        var provider = CreateProvider(databaseType);

        builder.AppendLine("/* Generated by DataLinq schema diff. Review before executing. */");
        builder.AppendLine();

        if (differences.Count == 0)
        {
            builder.AppendLine("-- No schema drift detected.");
            return builder.ToString();
        }

        foreach (var difference in differences)
        {
            switch (difference.Kind)
            {
                case SchemaDifferenceKind.MissingTable when difference.ModelDefinition is TableDefinition table:
                    AppendCreateTable(builder, provider, difference, table);
                    break;

                case SchemaDifferenceKind.MissingColumn when difference.ModelDefinition is ColumnDefinition column:
                    AppendAddColumn(builder, provider, difference, column);
                    break;

                case SchemaDifferenceKind.MissingIndex when difference.ModelDefinition is ColumnIndex index:
                    AppendCreateIndex(builder, provider, difference, index);
                    break;

                default:
                    AppendCommentedDifference(builder, difference);
                    break;
            }
        }

        return builder.ToString();
    }

    private static SqlDiffProvider CreateProvider(DatabaseType databaseType) =>
        databaseType switch
        {
            DatabaseType.SQLite => new SqlDiffProvider(
                DatabaseType.SQLite,
                '"',
                column => new SqlFromSQLiteFactory().GetDbType(column),
                column => new SqlFromSQLiteFactory().GetDefaultValue(column)),

            DatabaseType.MySQL => new SqlDiffProvider(
                DatabaseType.MySQL,
                '`',
                column => new SqlFromMySqlFactory().GetDbType(column),
                column => new SqlFromMySqlFactory().GetDefaultValue(column)),

            DatabaseType.MariaDB => new SqlDiffProvider(
                DatabaseType.MariaDB,
                '`',
                column => new SqlFromMariaDBFactory().GetDbType(column),
                column => new SqlFromMariaDBFactory().GetDefaultValue(column)),

            _ => throw new NotSupportedException($"Schema diff script generation is not supported for {databaseType}.")
        };

    private static void AppendCreateTable(
        StringBuilder builder,
        SqlDiffProvider provider,
        SchemaDifference difference,
        TableDefinition table)
    {
        AppendDifferenceHeader(builder, "additive", difference);
        builder.AppendLine($"CREATE TABLE IF NOT EXISTS {provider.Quote(table.DbName)} (");

        var rows = new List<string>();
        var inlineSinglePrimaryKey = provider.DatabaseType == DatabaseType.SQLite && table.PrimaryKeyColumns.Length == 1;
        foreach (var column in table.Columns.OrderBy(x => x.Index))
            rows.Add("  " + RenderColumn(provider, column, inlineSinglePrimaryKey, forAlterTable: false));

        if (!inlineSinglePrimaryKey && table.PrimaryKeyColumns.Length > 0)
            rows.Add($"  PRIMARY KEY ({provider.QuoteList(table.PrimaryKeyColumns.Select(x => x.DbName))})");

        builder.AppendLine(string.Join(",\n", rows));
        builder.AppendLine(");");
        builder.AppendLine();

        foreach (var index in GetCreatableIndexes(table))
            AppendCreateIndex(builder, provider, null, index);
    }

    private static void AppendAddColumn(
        StringBuilder builder,
        SqlDiffProvider provider,
        SchemaDifference difference,
        ColumnDefinition column)
    {
        AppendDifferenceHeader(builder, "additive", difference);

        if (column.PrimaryKey)
        {
            builder.AppendLine("-- Manual action required: adding a primary-key column to an existing table is provider-specific and may require a table rebuild.");
            builder.AppendLine();
            return;
        }

        if (!column.Nullable && column.ValueProperty.GetDefaultAttribute() == null)
            builder.AppendLine("-- WARNING: adding a NOT NULL column without a default can fail on non-empty tables.");

        builder.AppendLine($"ALTER TABLE {provider.Quote(column.Table.DbName)} ADD COLUMN {RenderColumn(provider, column, inlineSinglePrimaryKey: false, forAlterTable: true)};");
        builder.AppendLine();
    }

    private static void AppendCreateIndex(
        StringBuilder builder,
        SqlDiffProvider provider,
        SchemaDifference? difference,
        ColumnIndex index)
    {
        if (difference != null)
            AppendDifferenceHeader(builder, "additive", difference);

        if (!IsCreatableIndex(provider.DatabaseType, index))
        {
            builder.AppendLine($"-- Manual action required: index '{index.Name}' uses unsupported diff-script shape {index.Characteristic}/{index.Type}.");
            builder.AppendLine();
            return;
        }

        var unique = index.Characteristic == IndexCharacteristic.Unique ? "UNIQUE " : "";
        var columns = provider.QuoteList(index.Columns.Select(x => x.DbName));

        if (provider.DatabaseType == DatabaseType.SQLite)
        {
            builder.AppendLine($"CREATE {unique}INDEX IF NOT EXISTS {provider.Quote(index.Name)} ON {provider.Quote(index.Table.DbName)} ({columns});");
        }
        else
        {
            var usingClause = index.Type == IndexType.BTREE || index.Type == IndexType.HASH
                ? $" USING {index.Type.ToString().ToUpperInvariant()}"
                : "";
            builder.AppendLine($"CREATE {unique}INDEX {provider.Quote(index.Name)}{usingClause} ON {provider.Quote(index.Table.DbName)} ({columns});");
        }

        builder.AppendLine();
    }

    private static string RenderColumn(
        SqlDiffProvider provider,
        ColumnDefinition column,
        bool inlineSinglePrimaryKey,
        bool forAlterTable)
    {
        var parts = new List<string>
        {
            provider.Quote(column.DbName),
            FormatColumnType(provider, column)
        };

        var dbType = provider.GetDbType(column);
        if (provider.DatabaseType is DatabaseType.MySQL or DatabaseType.MariaDB && dbType.Signed == false)
            parts.Add("UNSIGNED");

        if (!forAlterTable && inlineSinglePrimaryKey && column.PrimaryKey)
            parts.Add("PRIMARY KEY");

        if (provider.DatabaseType == DatabaseType.SQLite && !forAlterTable && inlineSinglePrimaryKey && column.AutoIncrement)
            parts.Add("AUTOINCREMENT");

        var defaultValue = provider.GetDefaultValue(column);
        if (defaultValue != null)
            parts.Add($"DEFAULT {defaultValue}");

        parts.Add(column.PrimaryKey ? "NOT NULL" : column.Nullable ? "NULL" : "NOT NULL");

        if (provider.DatabaseType is DatabaseType.MySQL or DatabaseType.MariaDB && column.AutoIncrement)
            parts.Add("AUTO_INCREMENT");

        return string.Join(" ", parts);
    }

    private static string FormatColumnType(SqlDiffProvider provider, ColumnDefinition column)
    {
        var dbType = provider.GetDbType(column);
        var typeName = dbType.Name.ToUpperInvariant();

        if (provider.DatabaseType == DatabaseType.SQLite)
            return typeName;

        if (dbType.Name.Equals("enum", StringComparison.OrdinalIgnoreCase) && column.ValueProperty.EnumProperty.HasValue)
        {
            var values = column.ValueProperty.EnumProperty.Value.CsValuesOrDbValues
                .Select(x => QuoteSqlString(x.name));
            return $"{typeName}({string.Join(",", values)})";
        }

        if (MySqlNoLengthTypes.Contains(dbType.Name, StringComparer.OrdinalIgnoreCase) || !dbType.Length.HasValue || dbType.Length == 0)
            return typeName;

        if (dbType.Decimals.HasValue)
            return $"{typeName}({dbType.Length.Value.ToString(CultureInfo.InvariantCulture)},{dbType.Decimals.Value.ToString(CultureInfo.InvariantCulture)})";

        return $"{typeName}({dbType.Length.Value.ToString(CultureInfo.InvariantCulture)})";
    }

    private static IEnumerable<ColumnIndex> GetCreatableIndexes(TableDefinition table) =>
        table.ColumnIndices
            .Where(x => x.Characteristic is IndexCharacteristic.Simple or IndexCharacteristic.Unique)
            .OrderBy(x => x.Name, StringComparer.Ordinal);

    private static bool IsCreatableIndex(DatabaseType databaseType, ColumnIndex index)
    {
        if (index.Characteristic is not (IndexCharacteristic.Simple or IndexCharacteristic.Unique))
            return false;

        if (databaseType == DatabaseType.SQLite)
            return index.Type == IndexType.BTREE;

        return index.Type is IndexType.BTREE or IndexType.HASH;
    }

    private static void AppendDifferenceHeader(StringBuilder builder, string category, SchemaDifference difference)
    {
        builder.AppendLine($"-- {category.ToUpperInvariant()} {difference.Kind} {difference.Path}");
        builder.AppendLine($"-- {EscapeSqlComment(difference.Message)}");
    }

    private static void AppendCommentedDifference(StringBuilder builder, SchemaDifference difference)
    {
        var category = difference.Safety switch
        {
            SchemaDifferenceSafety.Destructive => "DESTRUCTIVE",
            SchemaDifferenceSafety.Ambiguous => "AMBIGUOUS",
            SchemaDifferenceSafety.Informational => "INFORMATIONAL",
            _ => "UNSUPPORTED"
        };

        builder.AppendLine($"-- {category} {difference.Kind} {difference.Path}");
        builder.AppendLine($"-- {EscapeSqlComment(difference.Message)}");
        builder.AppendLine("-- Manual review required. No SQL was generated for this difference.");
        builder.AppendLine();
    }

    private static string EscapeSqlComment(string value) =>
        value.Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private static string QuoteSqlString(string value) =>
        $"'{value.Replace("'", "''", StringComparison.Ordinal)}'";

    private sealed class SqlDiffProvider
    {
        public SqlDiffProvider(
            DatabaseType databaseType,
            char quoteCharacter,
            Func<ColumnDefinition, DatabaseColumnType> getDbType,
            Func<ColumnDefinition, string?> getDefaultValue)
        {
            DatabaseType = databaseType;
            QuoteCharacter = quoteCharacter;
            GetDbType = getDbType;
            GetDefaultValue = getDefaultValue;
        }

        public DatabaseType DatabaseType { get; }
        public char QuoteCharacter { get; }
        public Func<ColumnDefinition, DatabaseColumnType> GetDbType { get; }
        public Func<ColumnDefinition, string?> GetDefaultValue { get; }

        public string Quote(string identifier) =>
            $"{QuoteCharacter}{identifier.Replace(QuoteCharacter.ToString(), new string(QuoteCharacter, 2), StringComparison.Ordinal)}{QuoteCharacter}";

        public string QuoteList(IEnumerable<string> identifiers) =>
            string.Join(", ", identifiers.Select(Quote));
    }
}
