### YamlMime:ApiPage
title: Class DataLinqLoggingConfiguration
body:
- api1: Class DataLinqLoggingConfiguration
  id: DataLinq_Logging_DataLinqLoggingConfiguration
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L6
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration
    commentId: T:DataLinq.Logging.DataLinqLoggingConfiguration
- facts:
  - name: Namespace
    value:
      text: DataLinq.Logging
      url: DataLinq.Logging.html
  - name: Assembly
    value: DataLinq.dll
- code: public sealed class DataLinqLoggingConfiguration
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: DataLinqLoggingConfiguration
    url: DataLinq.Logging.DataLinqLoggingConfiguration.html
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Constructors
- api3: DataLinqLoggingConfiguration(ILoggerFactory)
  id: DataLinq_Logging_DataLinqLoggingConfiguration__ctor_Microsoft_Extensions_Logging_ILoggerFactory_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L6
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.#ctor(Microsoft.Extensions.Logging.ILoggerFactory)
    commentId: M:DataLinq.Logging.DataLinqLoggingConfiguration.#ctor(Microsoft.Extensions.Logging.ILoggerFactory)
- code: public DataLinqLoggingConfiguration(ILoggerFactory loggerFactory)
- h4: Parameters
- parameters:
  - name: loggerFactory
    type:
    - text: ILoggerFactory
      url: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.iloggerfactory
- h2: Properties
- api3: CacheLogger
  id: DataLinq_Logging_DataLinqLoggingConfiguration_CacheLogger
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L13
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.CacheLogger
    commentId: P:DataLinq.Logging.DataLinqLoggingConfiguration.CacheLogger
- code: public ILogger CacheLogger { get; }
- h4: Property Value
- parameters:
  - type:
    - text: ILogger
      url: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger
- api3: LoggerFactory
  id: DataLinq_Logging_DataLinqLoggingConfiguration_LoggerFactory
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L10
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.LoggerFactory
    commentId: P:DataLinq.Logging.DataLinqLoggingConfiguration.LoggerFactory
- code: public ILoggerFactory LoggerFactory { get; }
- h4: Property Value
- parameters:
  - type:
    - text: ILoggerFactory
      url: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.iloggerfactory
- api3: NullConfiguration
  id: DataLinq_Logging_DataLinqLoggingConfiguration_NullConfiguration
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L8
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.NullConfiguration
    commentId: P:DataLinq.Logging.DataLinqLoggingConfiguration.NullConfiguration
- code: public static DataLinqLoggingConfiguration NullConfiguration { get; }
- h4: Property Value
- parameters:
  - type:
    - text: DataLinqLoggingConfiguration
      url: DataLinq.Logging.DataLinqLoggingConfiguration.html
- api3: SqlCommandLogger
  id: DataLinq_Logging_DataLinqLoggingConfiguration_SqlCommandLogger
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L11
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.SqlCommandLogger
    commentId: P:DataLinq.Logging.DataLinqLoggingConfiguration.SqlCommandLogger
- code: public ILogger SqlCommandLogger { get; }
- h4: Property Value
- parameters:
  - type:
    - text: ILogger
      url: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger
- api3: TransactionLogger
  id: DataLinq_Logging_DataLinqLoggingConfiguration_TransactionLogger
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Logging/DataLinqLoggingConfiguration.cs#L12
  metadata:
    uid: DataLinq.Logging.DataLinqLoggingConfiguration.TransactionLogger
    commentId: P:DataLinq.Logging.DataLinqLoggingConfiguration.TransactionLogger
- code: public ILogger TransactionLogger { get; }
- h4: Property Value
- parameters:
  - type:
    - text: ILogger
      url: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger
languageId: csharp
