### YamlMime:ApiPage
title: Class ConfigReader
body:
- api1: Class ConfigReader
  id: DataLinq_Config_ConfigReader
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/ConfigReader.cs#L10
  metadata:
    uid: DataLinq.Config.ConfigReader
    commentId: T:DataLinq.Config.ConfigReader
- facts:
  - name: Namespace
    value:
      text: DataLinq.Config
      url: DataLinq.Config.html
  - name: Assembly
    value: DataLinq.dll
- code: public static class ConfigReader
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: ConfigReader
    url: DataLinq.Config.ConfigReader.html
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.MemberwiseClone()
    url: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Methods
- api3: ParseDatabaseType(string?)
  id: DataLinq_Config_ConfigReader_ParseDatabaseType_System_String_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/ConfigReader.cs#L12
  metadata:
    uid: DataLinq.Config.ConfigReader.ParseDatabaseType(System.String)
    commentId: M:DataLinq.Config.ConfigReader.ParseDatabaseType(System.String)
- code: public static DatabaseType? ParseDatabaseType(string? typeName)
- h4: Parameters
- parameters:
  - name: typeName
    type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
    - '?'
- h4: Returns
- parameters:
  - type:
    - DatabaseType
    - '?'
- api3: ParseFileEncoding(string)
  id: DataLinq_Config_ConfigReader_ParseFileEncoding_System_String_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/ConfigReader.cs#L28
  metadata:
    uid: DataLinq.Config.ConfigReader.ParseFileEncoding(System.String)
    commentId: M:DataLinq.Config.ConfigReader.ParseFileEncoding(System.String)
- code: public static Encoding ParseFileEncoding(string encoding)
- h4: Parameters
- parameters:
  - name: encoding
    type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
- h4: Returns
- parameters:
  - type:
    - text: Encoding
      url: https://learn.microsoft.com/dotnet/api/system.text.encoding
- api3: Read(string)
  id: DataLinq_Config_ConfigReader_Read_System_String_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/ConfigReader.cs#L39
  metadata:
    uid: DataLinq.Config.ConfigReader.Read(System.String)
    commentId: M:DataLinq.Config.ConfigReader.Read(System.String)
- code: public static ConfigFile Read(string path)
- h4: Parameters
- parameters:
  - name: path
    type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
- h4: Returns
- parameters:
  - type:
    - text: ConfigFile
      url: DataLinq.Config.ConfigFile.html
languageId: csharp
