### YamlMime:ApiPage
title: Namespace DataLinq.Config
body:
- api1: Namespace DataLinq.Config
  id: DataLinq_Config
  metadata:
    uid: DataLinq.Config
    commentId: N:DataLinq.Config
- h3: Classes
- parameters:
  - type:
      text: ConfigFile
      url: DataLinq.Config.ConfigFile.html
  - type:
      text: ConfigFileDatabase
      url: DataLinq.Config.ConfigFileDatabase.html
  - type:
      text: ConfigFileDatabaseConnection
      url: DataLinq.Config.ConfigFileDatabaseConnection.html
  - type:
      text: ConfigReader
      url: DataLinq.Config.ConfigReader.html
  - type:
      text: DataLinqConfig
      url: DataLinq.Config.DataLinqConfig.html
  - type:
      text: DataLinqConnectionString
      url: DataLinq.Config.DataLinqConnectionString.html
    description: Represents a connection string and provides methods to access its components.
  - type:
      text: DataLinqDatabaseConfig
      url: DataLinq.Config.DataLinqDatabaseConfig.html
  - type:
      text: DataLinqDatabaseConnection
      url: DataLinq.Config.DataLinqDatabaseConnection.html
languageId: csharp
