### YamlMime:ApiPage
title: Class DataLinqDatabaseConnection
body:
- api1: Class DataLinqDatabaseConnection
  id: DataLinq_Config_DataLinqDatabaseConnection
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L209
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection
    commentId: T:DataLinq.Config.DataLinqDatabaseConnection
- facts:
  - name: Namespace
    value:
      text: DataLinq.Config
      url: DataLinq.Config.html
  - name: Assembly
    value: DataLinq.dll
- code: 'public record DataLinqDatabaseConnection : IEquatable<DataLinqDatabaseConnection>'
- h4: Inheritance
- inheritance:
  - text: object
    url: https://learn.microsoft.com/dotnet/api/system.object
  - text: DataLinqDatabaseConnection
    url: DataLinq.Config.DataLinqDatabaseConnection.html
- h4: Implements
- list:
  - text: IEquatable<DataLinqDatabaseConnection>
    url: https://learn.microsoft.com/dotnet/api/system.iequatable-1
- h4: Inherited Members
- list:
  - text: object.Equals(object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - text: object.Equals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - text: object.GetHashCode()
    url: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - text: object.GetType()
    url: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - text: object.MemberwiseClone()
    url: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - text: object.ReferenceEquals(object?, object?)
    url: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - text: object.ToString()
    url: https://learn.microsoft.com/dotnet/api/system.object.tostring
- h2: Constructors
- api3: DataLinqDatabaseConnection(DataLinqDatabaseConfig, ConfigFileDatabaseConnection)
  id: DataLinq_Config_DataLinqDatabaseConnection__ctor_DataLinq_Config_DataLinqDatabaseConfig_DataLinq_Config_ConfigFileDatabaseConnection_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L227
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.#ctor(DataLinq.Config.DataLinqDatabaseConfig,DataLinq.Config.ConfigFileDatabaseConnection)
    commentId: M:DataLinq.Config.DataLinqDatabaseConnection.#ctor(DataLinq.Config.DataLinqDatabaseConfig,DataLinq.Config.ConfigFileDatabaseConnection)
- code: public DataLinqDatabaseConnection(DataLinqDatabaseConfig databaseConfig, ConfigFileDatabaseConnection connection)
- h4: Parameters
- parameters:
  - name: databaseConfig
    type:
    - text: DataLinqDatabaseConfig
      url: DataLinq.Config.DataLinqDatabaseConfig.html
  - name: connection
    type:
    - text: ConfigFileDatabaseConnection
      url: DataLinq.Config.ConfigFileDatabaseConnection.html
- h2: Properties
- api3: ConnectionString
  id: DataLinq_Config_DataLinqDatabaseConnection_ConnectionString
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L215
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.ConnectionString
    commentId: P:DataLinq.Config.DataLinqDatabaseConnection.ConnectionString
- code: public DataLinqConnectionString ConnectionString { get; }
- h4: Property Value
- parameters:
  - type:
    - text: DataLinqConnectionString
      url: DataLinq.Config.DataLinqConnectionString.html
- api3: DataSourceName
  id: DataLinq_Config_DataLinqDatabaseConnection_DataSourceName
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L214
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.DataSourceName
    commentId: P:DataLinq.Config.DataLinqDatabaseConnection.DataSourceName
- code: public string DataSourceName { get; }
- h4: Property Value
- parameters:
  - type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
- api3: DatabaseConfig
  id: DataLinq_Config_DataLinqDatabaseConnection_DatabaseConfig
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L211
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.DatabaseConfig
    commentId: P:DataLinq.Config.DataLinqDatabaseConnection.DatabaseConfig
- code: public DataLinqDatabaseConfig DatabaseConfig { get; }
- h4: Property Value
- parameters:
  - type:
    - text: DataLinqDatabaseConfig
      url: DataLinq.Config.DataLinqDatabaseConfig.html
- api3: Type
  id: DataLinq_Config_DataLinqDatabaseConnection_Type
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L213
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.Type
    commentId: P:DataLinq.Config.DataLinqDatabaseConnection.Type
- code: public DatabaseType Type { get; }
- h4: Property Value
- parameters:
  - type:
    - DatabaseType
- h2: Methods
- api3: GetRootedPath(string)
  id: DataLinq_Config_DataLinqDatabaseConnection_GetRootedPath_System_String_
  src: https://github.com/bazer/DataLinq/blob/master/src/DataLinq/Config/DataLinqConfig.cs#L217
  metadata:
    uid: DataLinq.Config.DataLinqDatabaseConnection.GetRootedPath(System.String)
    commentId: M:DataLinq.Config.DataLinqDatabaseConnection.GetRootedPath(System.String)
- code: public string GetRootedPath(string basePath)
- h4: Parameters
- parameters:
  - name: basePath
    type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
- h4: Returns
- parameters:
  - type:
    - text: string
      url: https://learn.microsoft.com/dotnet/api/system.string
languageId: csharp
